---
- name: Add timberio chart repo
  community.kubernetes.helm_repository:
    state: present
    name: timberio
    repo_url: "https://packages.timber.io/helm/latest"

- name: Add bitnami chart repo
  community.kubernetes.helm_repository:
    state: present
    name: bitnami
    repo_url: "https://charts.bitnami.com/bitnami"

- name: Add vector chart repo
  community.kubernetes.helm_repository:
    state: present
    name: vector
    repo_url: "https://helm.vector.dev"

- name: Deploy kafka
  community.kubernetes.helm:
    state: "{{ kafka_state }}"
    name: kafka
    namespace: "{{ namespace }}"
    create_namespace: true
    chart_ref: bitnami/kafka
    chart_version: 18.0.0
    values: "{{ lookup('template', 'kafka-values.yaml.j2') | from_yaml | combine(kafka_chart_values, recursive=True) }}"
    wait: "{{ wait }}"
    wait_timeout: 15m

# - name: Deploy elasticsearch
#   community.kubernetes.helm:
#     state: "{{ elasticsearch_state }}"
#     name: elasticsearch
#     namespace: "{{ namespace }}"
#     create_namespace: true
#     chart_ref: bitnami/elasticsearch
#     chart_version: 18.2.15
#     values: "{{ lookup('template', 'elasticsearch-values.yaml.j2') | from_yaml | combine(elasticsearch_chart_values, recursive=True) }}"
#     wait: "{{ wait }}"
#     wait_timeout: 15m

- name: Deploy vector
  community.kubernetes.helm:
    state: "{{ vector_state }}"
    name: vector
    namespace: "{{ namespace }}"
    create_namespace: true
    chart_ref: vector/vector
    chart_version: 0.13.2
    values: "{{ lookup('template', 'vector-values.yaml.j2', variable_start_string='[%', variable_end_string='%]') | from_yaml | combine(vector_chart_values, recursive=True) }}"
